[package]
authors = ["Tom Houlé <tom@tomhoule.com>"]
name = "fragments-cli"
version = "0.1.0"

[build-dependencies]
prost-build = "0.3.2"

[dependencies]
bytes = "0.4.7"
failure = "*"
prost = "0.3.2"
prost-derive = "0.3.2"
rocksdb = "0.10.0"
structopt = "0.2.8"
